const OPERATIONS_TYPES = {
  ADD_LEFT_VALUE: 'ADD_LEFT_VALUE',
  ADD_RIGHT_VALUE: 'ADD_RIGHT_VALUE',
  ADD_OPERATOR: 'ADD_OPERATOR',
  ADD_RESULT: 'ADD_RESULT',
  REMOVE_LEFT_VALUE: 'REMOVE_LEFT_VALUE',
  REMOVE_RIGHT_VALUE: 'REMOVE_RIGHT_VALUE',
  REMOVE_RESULT: 'REMOVE_RESULT',
  REMOVE_OPERATOR: 'REMOVE_OPERATOR',
  NEW_OPERATION_FROM_RESULT: 'NEW_OPERATION_FROM_RESULT',
  NEW_OPERATION: 'NEW_OPERATION',
};

export default OPERATIONS_TYPES;
